# Template docker-push

# This template allows you to build and push your docker image to a Docker Hub account.
# The workflow allows running tests, code linting and security scans on feature branches (as well as master).
# The docker image will be validated and pushed to the docker registry after the code is merged to master.

# Prerequisites: $DOCKERHUB_USERNAME, $DOCKERHUB_PASSWORD setup as deployment variables

options:
  docker: true

pipelines:
  custom:
    hello-sh:
      - step:
          deployment: hello-sh
          name: build and push 'hello-sh'
          image: atlassian/default-image:4
          script:
            - echo $DOCKER_USERNAME
            - echo $DOCKER_PASSWORD
            - ./build-image.sh
    hello-java:
      - step:
          deployment: hello-java
          name: build and push 'hello-java'
          image: eclipse-temurin:21-jdk
          script:
            - ./build-image.sh
