# Definitions of Bit-Bucket pipelines to build and push docker-images
# Prerequisites: $DOCKER_USERNAME, $DOCKER_PASSWORD setup as Bit-Bucket repository-variables

options:
  docker: true

pipelines:
  custom:
    hello-sh:
      - step: &build-step--hello-sh
          deployment: hello-sh
          name: build and push 'hello-sh'
          image: atlassian/default-image:4
          script:
            - ./build-image.sh
    hello-java:
      - step: &build-step--hello-java
          deployment: hello-java
          name: build and push 'hello-java'
          image: eclipse-temurin:21-jdk
          script:
            - ./build-image.sh
    hello-maven:
      - step: &build-step--hello-maven
          deployment: hello-maven
          name: build and push 'hello-maven'
          image: maven:3.9.6-eclipse-temurin-21
          caches:
            - maven
          script:
            - ./build-image.sh
  default:
    - parallel:
        steps:
          - step:
              name: info about working steps
              script:
                - echo "... only ons step is working now ..."
#          - step: *build-step--hello-sh
#          - step: *build-step--hello-java
#          - step: *build-step--hello-maven
          - step:
              deployment: hello-gradle
              name: build and push 'hello-gradle'
              image: eclipse-temurin:21-jdk
              script:
                - echo "... starting '$DEPLOYMEMT_NAME' ..."
                - ./gradlew --version
                - ./gradlew tasks --all
