# Template docker-push

# This template allows you to build and push your docker image to a Docker Hub account.
# The workflow allows running tests, code linting and security scans on feature branches (as well as master).
# The docker image will be validated and pushed to the docker registry after the code is merged to master.

# Prerequisites: $DOCKERHUB_USERNAME, $DOCKERHUB_PASSWORD setup as deployment variables

image: atlassian/default-image:3

pipelines:
  default:
    - step:
        deployment: Test
        script:
          - docker version
          - chmod +x ./hello.sh
          - echo "executing before bulding the docker-image:" && ./hello.sh
          - docker build . --tage krmdemo/thymeleaf-base:1.0
          - docker images
          - docker login --username "krmdemo" --password "1qa@WS0ok(IJ"
          - docker push krmdemo/thymeleaf-base:1.0
        services:
          - docker