name: 'Manual Build & Push'
on: workflow_dispatch
jobs:
  hello-sh:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the latest changes
      uses: actions/checkout@v4
    - name: install buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    - name: invoke 'buildx-image.sh'
      env:
        DEPLOYMENT_NAME: hello-sh
        DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: ./buildx-image.sh
  hello-java:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the latest changes
        uses: actions/checkout@v4
      - name: using proper version of java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: invoke 'buildx-image.sh'
        env:
          DEPLOYMENT_NAME: hello-java
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./buildx-image.sh
  hello-maven:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the latest changes
        uses: actions/checkout@v4
      - name: using proper version of java and maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: invoke 'buildx-image.sh'
        env:
          DEPLOYMENT_NAME: hello-maven
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./buildx-image.sh
  hello-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the latest changes
        uses: actions/checkout@v4
      - name: using proper version of java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: setup gradle
        uses: gradle/gradle-build-action@v2
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: invoke 'buildx-image.sh'
        env:
          DEPLOYMENT_NAME: hello-gradle
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./buildx-image.sh
      - name: analyze with sonar-cloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info
