name: 'Manual Build & Push'
on: workflow_dispatch
jobs:
  hello-sh:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the latest changes
      uses: actions/checkout@v4
    - name: pre-build hello-sh
      run: |
        echo "The content of current dir '$(pwd)':"
        ls -laxo
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: pre-push hello-sh
      run: |
        docker buildx version
        docker buildx ls
    - name: Generate list using Markdown
      run: |
        echo "Some results ..." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
        echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
