name: 'Manual Build & Push'
on: workflow_dispatch
jobs:
  hello-sh:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the latest changes
      uses: actions/checkout@v4
    - name: install buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    - name: invoke 'buildx-image.sh'
      env:
        DEPLOYMENT_NAME: hello-sh
        DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: ./buildx-image.sh
  hello-java:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the latest changes
        uses: actions/checkout@v4
      - name: using proper version of java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: invoke 'buildx-image.sh'
        env:
          DEPLOYMENT_NAME: hello-java
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "attempt to invoke 'javac':"
          javac -version
          which javac
          echo "JAVA_HOME = $JAVA_HOME"
          echo "attempt to invoke './mvnw':"
          ./mvnw buildplan:list
          echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
          ./buildx-image.sh
