name: 'Manual Build & Push'
on: workflow_dispatch
jobs:
  hello-sh:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the latest changes
      uses: actions/checkout@v4
    - name: install buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    - name: pre-build hello-sh
      # env:
      #   GH_BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      #   GH_BUILD_NUMBER: ${{ github.run_number }}
      #   GH_SHA_SHORT: 
      run: ./buildx-image.sh
    - name: some markdown with summary
      env:
        GH_BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
        GH_BUILD_NUMBER: ${{ github.run_number }}
      run: |
        echo "Some results in branch ${GH_BRANCH_NAME}(${GH_BUILD_NUMBER})" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
        echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
